server:
  port: 8081

spring:
  application:
    name: mori-auth-service
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: mori-config-server